
macro(DETERMINE_GCC_SYSTEM_INCLUDE_DIRS _lang _compiler _flags _result)
    file(WRITE "${CMAKE_BINARY_DIR}/CMakeFiles/dummy" "\n")
    separate_arguments(_buildFlags UNIX_COMMAND "${_flags}")
    execute_process(COMMAND ${_compiler} ${_buildFlags} -v -E -x ${_lang} -dD dummy
                    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/CMakeFiles OUTPUT_QUIET
                    ERROR_VARIABLE _gccOutput)
    file(REMOVE "${CMAKE_BINARY_DIR}/CMakeFiles/dummy")
    if ("${_gccOutput}" MATCHES "> search starts here[^\n]+\n *(.+) *\n *End of (search) list")
        set(${_result} ${CMAKE_MATCH_1})
        string(REPLACE "\n" "" ${_result} "${${_result}}")
        separate_arguments(${_result})
    endif ()
endmacro()

macro(GET_COMPILER_INCLUDE_LIST_RAW _compiler _out_var)
    DETERMINE_GCC_SYSTEM_INCLUDE_DIRS("c" ${_compiler} "${CMAKE_C_FLAGS}" MY_COMPILER_LIST_1)
    DETERMINE_GCC_SYSTEM_INCLUDE_DIRS("c++" ${_compiler} "${CMAKE_C_FLAGS}" MY_COMPILER_LIST_2)
    foreach(MYFILE ${MY_COMPILER_LIST_1} ${MY_COMPILER_LIST_2})
        if (MINGW)
            FIX_WINDOWS_PATHS(MYFILE)
        endif()
        get_filename_component(MYFILE "${MYFILE}" ABSOLUTE)
        list(APPEND ${_out_var} "\"-I${MYFILE}\"")
    endforeach()
endmacro()

macro(GET_COMPILER_PATHS _out_var)
    
    # DETERMINE_GCC_SYSTEM_INCLUDE_DIRS("c" "clang" "${CMAKE_C_FLAGS}" MY_COMPILER_LIST_1)
    # DETERMINE_GCC_SYSTEM_INCLUDE_DIRS("c++" "clang" "${CMAKE_C_FLAGS}" MY_COMPILER_LIST_2)
    # foreach(MYFILE ${MY_COMPILER_LIST_1} ${MY_COMPILER_LIST_2})
    #     if (MINGW)
    #         FIX_WINDOWS_PATHS(MYFILE)
    #     endif()
    #     get_filename_component(MYFILE "${MYFILE}" ABSOLUTE)
    #     list(APPEND MY_COMPILER_INCLUDE_LIST "\"-I${MYFILE}\"")
    # endforeach()
    # 
    # DETERMINE_GCC_SYSTEM_INCLUDE_DIRS("c" "gcc" "${CMAKE_C_FLAGS}" MY_COMPILER_LIST_1)
    # DETERMINE_GCC_SYSTEM_INCLUDE_DIRS("c++" "gcc" "${CMAKE_C_FLAGS}" MY_COMPILER_LIST_2)
    # foreach(MYFILE ${MY_COMPILER_LIST_1} ${MY_COMPILER_LIST_2})
    #     if (MINGW)
    #         FIX_WINDOWS_PATHS(MYFILE)
    #     endif()
    #     get_filename_component(MYFILE "${MYFILE}" ABSOLUTE)
    #     list(APPEND MY_COMPILER_INCLUDE_LIST  "\"-I${MYFILE}\"")
    # endforeach()

    GET_COMPILER_INCLUDE_LIST_RAW("clang" MY_COMPILER_INCLUDE_LIST)
    GET_COMPILER_INCLUDE_LIST_RAW("gcc" MY_COMPILER_INCLUDE_LIST)
    list(REMOVE_DUPLICATES MY_COMPILER_INCLUDE_LIST)
    foreach (MY_INCLUDE ${MY_COMPILER_INCLUDE_LIST})
        if (${_out_var})
            string(CONCAT ${_out_var} "${${_out_var}}" ", ${MY_INCLUDE}")
        else()
            string(CONCAT ${_out_var} "${${_out_var}}" "${MY_INCLUDE}")
        endif()
    endforeach()
    # list(JOIN MY_COMPILER_INCLUDE_LIST ", " ${_out_var})
endmacro()
